[package]
name = "ruztex"
version = "0.1.0"
edition = "2024"

[dependencies]
crossterm = "0.29.0"
lazy_static = "1.5.0"
once_cell = "1.21.3"
ratatui = "0.29.0"
regex = "1.11.1"
serde = "1.0.219"
serde_yaml = "0.9.34"
"unicode-segmentation" = "1.11.0"

[[bin]]
name = "ruztex"
path = "main.rs"
